version: "3"

networks:
  default:
    external: false

services:
  ganache:
    image: trufflesuite/ganache-cli:v6.9.1
    ports:
      - '8545:8545'
    command: ganache-cli -s attestation
# mnemonic: endorse soccer immense wonder cheap crew hundred protect bunker lemon burden wash