version: "3"

networks:
  default:
    external: false

services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - '8545:8545'
    command: ganache-cli -s attestation -l 100000000000
# mnemonic: endorse soccer immense wonder cheap crew hundred protect bunker lemon burden wash